### ISSUE TITLE
NTSC and TV distortion do not work in Unity 5.3.5f1 personal [Fixed]

### ISSUE THREAD

**Issue by aspoet** [GreyGolem/EasyVHS#1]
When I apply the scripts to a camera or use the camera prefab that comes with the package, they do not work and display the following error logs:

The shader Hidden/NTSCShader (UnityEngine.Shader) on effect Main Camera (NTSC) is not supported on this platform!
UnityEngine.Debug:Log(Object)
UnityStandardAssets.ImageEffects.PostEffectsBase:CheckShaderAndCreateMaterial(Shader, Material) (at Assets/Standard Assets/Effects/ImageEffects/Scripts/PostEffectsBase.cs:29)
NTSC:CheckResources() (at Assets/EasyVHS/Scripts/NTSC.cs:24)
NTSC:OnRenderImage(RenderTexture, RenderTexture) (at Assets/EasyVHS/Scripts/NTSC.cs:39)

The image effect Main Camera (NTSC) has been disabled as it's not supported on the current platform.
UnityEngine.Debug:LogWarning(Object)
UnityStandardAssets.ImageEffects.PostEffectsBase:ReportAutoDisable() (at Assets/Standard Assets/Effects/ImageEffects/Scripts/PostEffectsBase.cs:138)
NTSC:CheckResources() (at Assets/EasyVHS/Scripts/NTSC.cs:27)
NTSC:OnRenderImage(RenderTexture, RenderTexture) (at Assets/EasyVHS/Scripts/NTSC.cs:39)

The shader Hidden/TVDistortionShader (UnityEngine.Shader) on effect Main Camera (TVDistortion) is not supported on this platform!
UnityEngine.Debug:Log(Object)
UnityStandardAssets.ImageEffects.PostEffectsBase:CheckShaderAndCreateMaterial(Shader, Material) (at Assets/Standard Assets/Effects/ImageEffects/Scripts/PostEffectsBase.cs:29)
TVDistortion:CheckResources() (at Assets/EasyVHS/Scripts/TVDistortion.cs:35)
TVDistortion:OnRenderImage(RenderTexture, RenderTexture) (at Assets/EasyVHS/Scripts/TVDistortion.cs:51)

NullReferenceException: Object reference not set to an instance of an object
TVDistortion.CheckResources () (at Assets/EasyVHS/Scripts/TVDistortion.cs:36)
TVDistortion.OnRenderImage (UnityEngine.RenderTexture source, UnityEngine.RenderTexture destination) (at Assets/EasyVHS/Scripts/TVDistortion.cs:51)

It would be great if this could be resolved.
Hoping for an update
Alex

**Comment by GreyGolem** [comment]
Thank you for reporting this issue.
The solution will be available as soon as the Unity team reviews our newest revision of the package.

**Comment by aspoet** [comment]
Super nice to hear! Changed my rating back since I have no doubt that it was just some code reference Unity broke in the latest update and you guys will fix it. Thank you very much! Ill close this once the update pops up 👍

**Comment by GreyGolem** [comment]
Thank you very much. The problem was with shader constants, looks like they can no longer be declared outside of functions and they were not being picked up.
